### ISSUE TITLE
Plotting ellipses on PCA off centre

### ISSUE THREAD

**Issue by low-sky** [Astroua/TurbuStat#211]
The fitted ellipses to the Orion 12CO HERA data are offset from the regions being fit.  
<img width="595" alt="screen shot 2019-02-13 at 15 20 07" src="https://user-images.githubusercontent.com/1139910/52742188-3661d000-2fa5-11e9-9f0c-01ccf36983e2.png">
The size scales appear appropriate so this is likely a plotting issue.

**Comment by e-koch** [comment]
Turned out just to be a plotting issue. Fixed in #205
