### ISSUE TITLE
Include sklearn, statsmodels as requirements

### ISSUE THREAD

**Issue by keflavich** [Astroua/TurbuStat#219]
A lot of functionality depends on sklearn, statsmodels, skimage, and maybe others, but these aren't listed as hard requirements; they probably should be.

**Comment by keflavich** [comment]
See https://github.com/teuben/dc2019/issues/5

**Comment by e-koch** [comment]
This was due to a packaging issue where the cython files didn't compile. The v1.1 release fixes this.
