### ISSUE TITLE
Spatial Power Spectrum Tutorial

### ISSUE THREAD

**Issue by patrickcgray** [Astroua/TurbuStat#225]
I'm trying to implement https://turbustat.readthedocs.io/en/latest/tutorials/statistics/pspec_example.html exactly as it is in the tutorial it gives me the error: `NameError: name 'u' is not defined`. Is this some units variable that should be imported with a different package or just something I'm missing?

You can see my code in colab here: https://colab.research.google.com/drive/1HBCMhyaFg55IAhRhNPODdV1yTu60QsWl.

**Comment by patrickcgray** [comment]
Ah okay I see it just needs: `import astropy.units as u` added to the code.

**Comment by e-koch** [comment]
That's right. Thanks for pointing this out! I'll add the missing import to the tutorial.
