### ISSUE TITLE
pip version too old

### ISSUE THREAD

**Issue by andrew-saydjari** [Astroua/TurbuStat#233]
Suggest a new pip version be pushed (or better yet a conda-forge package). Attempting to install via pip leads to "PEP 517 and cannot be installed directly" for which there will be soon no work around other than install for source.

**Comment by e-koch** [comment]
@andrew-saydjari -- thanks for reporting. I'm not able to reproduce this issue locally, though. Which python version are you using?

**Comment by andrew-saydjari** [comment]
Python 3.6.10

Importantly, I don't have a clean gcc installed in my main bin. It is the PEP 517 that prevents wheels and the fact that I cannot build directly.

**Comment by e-koch** [comment]
Ok thanks, I'll work on providing a larger set of release files on pip to avoid these issues.

Turbustat is for python 3, though. It should be fine for 3.6-3.8, but I'm not testing for 3.9 yet (scikit-image needs a new release first).

**Comment by andrew-saydjari** [comment]
Hmmm, ok. Somehow the errors during the attempted direct build were citing 2.7 related processes. Maybe somewhere to look. Thanks for looking into it.
