### ISSUE TITLE
PCA Subtract Channel Means

### ISSUE THREAD

**Issue by e-koch** [Astroua/TurbuStat#33]
Normalization for PCA is by column of data. Mean subtraction should be by channel instead of the whole cube.

**Comment by low-sky** [comment]
:+1:

See also new [PCA](https://github.com/low-sky/cloudpca)

**Comment by e-koch** [comment]
Also, should be dividing by N-1 instead of N for the sample covariance. The difference will matter for channels with only a few non-noisy pixels, not so much the others.

**Comment by low-sky** [comment]
@e-koch -- Note that the Brunt & Heyer PCA implementation does no mean subtraction in calculation of the data.  Bessel's correction wouldn't apply then, would it? I'm still testing this in [cloudpca](https://github.com/low-sky/cloudpca)

**Comment by e-koch** [comment]
@low-sky They subtract it in the [original paper](http://iopscience.iop.org/0004-637X/475/1/173/pdf/34400.pdf), but don't use Bessel's correction for the covariance. In the [2013 paper](http://mnras.oxfordjournals.org/content/433/1/117.full.pdf) I guess it is assumed?
I don't think the output can be called PCs if the channels aren't mean subtracted. It won't be the covariance matrix that's computed.

**Comment by low-sky** [comment]
@e-koch That's fair.  I'm going to see how it changes things.  The claim in [Brunt & Heyer (2003)](http://adsabs.harvard.edu/abs/2002ApJ...566..276B) is that it only shows up in the outer scale, which is what's important for the first eigenvalue and the size / line-width used in Dario's work.

**Comment by e-koch** [comment]
Addressed in #35 , #36.
