### ISSUE TITLE
Comparing cubes with different spatial dimensions

### ISSUE THREAD

**Issue by e-koch** [Astroua/TurbuStat#42]
Cramer and bispectrum fail in this case.

 - [x] Cramer can be fixed by sampling from the same percentage cut in the larger cube.

 - [x] Bispectrum is more difficult. It may be easiest to just match the dimensions to the smaller cube. This may not be the best method for preserving information though.

**Comment by low-sky** [comment]
Yeah, the bispectrum is tricky.  You want to compare over the same scales, so there's a regrid, then match to smallest.

**Comment by e-koch** [comment]
Addressed in #102, using the average bicoherence comparison.
