### ISSUE TITLE
Anderson-Darling Distances for PDFs

### ISSUE THREAD

**Issue by low-sky** [Astroua/TurbuStat#53]
@e-koch -- What do you think of using the AD statistic as a measure of things like the column density distribution functions?  The hard part with AD is getting the p-values, but we can just use the distance like all the other distances.

**Comment by e-koch** [comment]
@low-sky - Sure. We're doing the same thing when using the KS test, may as well complete the set.

**Comment by e-koch** [comment]
Addressed in #55
