### ISSUE TITLE
Non -distance outputs from TurbuStat

### ISSUE THREAD

**Issue by low-sky** [Astroua/TurbuStat#58]
Hi @e-koch  -- Many requests here to output lag vs. SCF value for the SCF and size vs. line width for PCA.

**Comment by e-koch** [comment]
@low-sky - Alright. This currently falls in the middle of the pack on the To-dos for TurbuStat.

 - [ ] Lag vs SCF output
 - [ ] size-line width output for PCA

**Comment by low-sky** [comment]
Wünderbar!  Thank you very much.

**Comment by e-koch** [comment]
@low-sky Any issues with just amalgamating cloudpca to the PCA class in here? Either that code is just added into this codebase or we make cloudpca a submodule.

**Comment by low-sky** [comment]
No issues but I did just get a peek at the Brunt and Heyer code so I think
we can stabilize the results and make them industry standard.  So let's
hold off until next week and revisit.

--
Sent from a mobile device.  Please excuse brevity.

On Jun 2, 2015, at 18:16, Eric Koch <notifications@github.com> wrote:

@low-sky <https://github.com/low-sky> Any issues with just amalgamating
cloudpca to the PCA class in here? Either that code is just added into this
codebase or we make cloudpca a submodule.

—
Reply to this email directly or view it on GitHub
<https://github.com/Astroua/TurbuStat/issues/58#issuecomment-108114479>.

**Comment by e-koch** [comment]
1D SCF spectrum vs lag implemented in #77

**Comment by e-koch** [comment]
PCA in #85
