### ISSUE TITLE
Wavelets only works with powers of 2

### ISSUE THREAD

**Issue by e-koch** [Astroua/TurbuStat#84]
Image sizes have to be powers of 2. This needs to be generalized for all shapes.

**Comment by keflavich** [comment]
It's for powers of 2,3,5, but I was recently pointed to this for optimizing ffts: https://github.com/scipy/scipy/blob/master/scipy/signal/signaltools.py#L211

**Comment by e-koch** [comment]
Perfect! Thanks!

**Comment by e-koch** [comment]
Fixed in #103
