### ISSUE TITLE
Implement PCA corrections

### ISSUE THREAD

**Issue by low-sky** [Astroua/TurbuStat#87]
Following the ellipse fitting method, the two principal axes `a` and `b` come out of the code.  These are then corrected to a size scale:
```
kappa = 0.8
e=(3/((kappa+2)*(kappa+3.)))**(1/kappa)
a_correct=(a**kappa-e**kappa)^(1/kappa)
b_correct=(b**kappa-e**kappa)^(1/kappa)
L = (0.5*a_correct**2 + 0.5*b_correct**2)**0.5
```
where `L` is the scale we want and the formulas and numbers come out of the Brunt 1999 PhD thesis.

**Comment by e-koch** [comment]
Added in #85
